#!/bin/bash
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 0 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 1 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 2 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 3 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 4 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 5 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 6 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 7 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 8 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 9 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 10 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 11 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 12 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 13 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 14 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 15 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 16 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 17 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 18 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 19 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 20 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 21 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 22 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 23 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 24 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 25 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 26 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 27 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 28 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 29 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 30 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 31 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 32 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 33 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 34 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 35 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 36 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 37 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 38 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 39 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 40 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 41 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 42 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 43 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 44 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 45 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 46 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 47 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 48 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 1 --seed 49 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 0 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 1 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 2 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 3 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 4 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 5 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 6 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 7 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 8 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 9 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 10 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 11 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 12 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 13 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 14 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 15 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 16 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 17 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 18 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 19 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 20 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 21 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 22 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 23 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 24 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 25 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 26 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 27 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 28 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 29 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 30 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 31 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 32 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 33 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 34 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 35 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 36 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 37 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 38 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 39 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 40 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 41 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 42 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 43 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 44 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 45 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 46 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 47 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 48 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 2 --seed 49 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 0 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 1 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 2 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 3 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 4 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 5 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 6 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 7 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 8 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 9 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 10 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 11 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 12 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 13 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 14 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 15 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 16 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 17 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 18 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 19 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 20 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 21 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 22 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 23 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 24 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 25 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 26 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 27 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 28 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 29 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 30 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 31 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 32 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 33 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 34 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 35 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 36 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 37 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 38 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 39 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 40 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 41 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 42 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 43 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 44 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 45 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 46 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 47 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 48 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 5 --seed 49 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 0 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 1 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 2 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 3 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 4 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 5 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 6 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 7 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 8 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 9 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 10 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 11 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 12 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 13 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 14 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 15 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 16 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 17 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 18 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 19 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 20 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 21 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 22 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 23 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 24 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 25 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 26 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 27 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 28 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 29 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 30 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 31 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 32 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 33 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 34 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 35 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 36 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 37 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 38 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 39 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 40 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 41 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 42 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 43 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 44 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 45 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 46 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 47 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 48 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 10 --seed 49 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 0 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 1 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 2 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 3 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 4 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 5 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 6 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 7 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 8 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 9 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 10 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 11 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 12 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 13 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 14 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 15 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 16 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 17 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 18 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 19 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 20 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 21 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 22 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 23 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 24 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 25 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 26 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 27 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 28 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 29 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 30 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 31 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 32 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 33 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 34 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 35 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 36 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 37 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 38 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 39 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 40 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 41 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 42 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 43 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 44 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 45 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 46 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 47 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 48 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 20 --seed 49 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 0 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 1 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 2 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 3 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 4 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 5 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 6 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 7 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 8 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 9 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 10 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 11 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 12 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 13 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 14 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 15 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 16 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 17 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 18 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 19 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 20 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 21 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 22 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 23 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 24 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 25 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 26 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 27 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 28 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 29 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 30 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 31 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 32 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 33 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 34 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 35 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 36 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 37 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 38 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 39 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 40 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 41 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 42 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 43 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 44 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 45 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 46 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 47 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 48 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 50 --seed 49 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 0 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 1 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 2 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 3 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 4 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 5 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 6 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 7 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 8 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 9 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 10 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 11 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 12 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 13 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 14 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 15 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 16 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 17 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 18 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 19 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 20 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 21 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 22 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 23 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 24 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 25 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 26 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 27 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 28 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 29 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 30 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 31 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 32 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 33 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 34 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 35 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 36 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 37 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 38 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 39 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 40 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 41 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 42 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 43 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 44 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 45 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 46 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 47 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 48 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 100 --seed 49 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 0 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 1 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 2 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 3 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 4 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 5 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 6 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 7 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 8 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 9 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 10 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 11 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 12 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 13 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 14 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 15 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 16 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 17 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 18 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 19 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 20 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 21 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 22 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 23 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 24 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 25 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 26 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 27 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 28 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 29 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 30 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 31 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 32 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 33 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 34 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 35 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 36 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 37 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 38 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 39 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 40 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 41 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 42 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 43 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 44 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 45 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 46 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 47 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 48 --ranklog
python main.py --rendermode none --colormap Accent --logfile ./output-rankanalysis-revision2/log.txt --dataset circle --criterion weight --numsamples 200 --seed 49 --ranklog
