#!/bin/bash
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 0
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 1
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 2
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 3
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 4
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 5
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 6
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 7
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 8
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 9
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 10
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 11
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 12
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 13
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 14
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 15
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 16
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 17
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 18
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 19
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 20
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 21
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 22
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 23
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 24
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 25
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 26
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 27
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 28
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 29
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 30
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 31
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 32
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 33
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 34
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 35
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 36
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 37
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 38
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 39
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 40
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 41
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 42
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 43
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 44
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 45
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 46
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 47
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 48
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 1 --seed 49
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 0
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 1
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 2
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 3
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 4
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 5
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 6
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 7
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 8
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 9
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 10
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 11
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 12
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 13
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 14
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 15
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 16
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 17
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 18
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 19
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 20
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 21
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 22
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 23
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 24
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 25
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 26
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 27
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 28
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 29
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 30
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 31
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 32
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 33
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 34
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 35
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 36
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 37
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 38
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 39
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 40
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 41
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 42
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 43
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 44
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 45
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 46
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 47
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 48
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 5 --seed 49
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 0
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 1
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 2
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 3
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 4
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 5
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 6
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 7
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 8
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 9
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 10
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 11
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 12
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 13
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 14
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 15
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 16
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 17
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 18
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 19
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 20
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 21
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 22
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 23
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 24
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 25
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 26
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 27
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 28
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 29
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 30
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 31
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 32
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 33
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 34
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 35
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 36
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 37
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 38
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 39
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 40
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 41
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 42
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 43
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 44
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 45
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 46
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 47
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 48
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 10 --seed 49
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 0
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 1
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 2
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 3
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 4
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 5
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 6
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 7
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 8
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 9
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 10
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 11
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 12
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 13
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 14
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 15
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 16
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 17
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 18
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 19
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 20
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 21
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 22
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 23
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 24
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 25
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 26
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 27
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 28
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 29
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 30
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 31
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 32
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 33
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 34
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 35
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 36
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 37
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 38
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 39
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 40
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 41
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 42
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 43
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 44
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 45
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 46
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 47
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 48
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 20 --seed 49
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 0
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 1
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 2
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 3
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 4
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 5
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 6
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 7
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 8
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 9
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 10
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 11
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 12
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 13
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 14
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 15
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 16
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 17
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 18
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 19
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 20
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 21
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 22
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 23
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 24
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 25
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 26
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 27
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 28
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 29
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 30
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 31
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 32
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 33
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 34
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 35
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 36
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 37
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 38
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 39
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 40
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 41
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 42
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 43
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 44
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 45
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 46
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 47
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 48
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 50 --seed 49
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 0
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 1
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 2
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 3
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 4
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 5
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 6
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 7
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 8
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 9
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 10
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 11
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 12
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 13
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 14
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 15
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 16
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 17
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 18
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 19
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 20
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 21
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 22
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 23
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 24
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 25
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 26
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 27
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 28
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 29
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 30
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 31
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 32
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 33
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 34
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 35
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 36
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 37
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 38
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 39
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 40
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 41
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 42
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 43
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 44
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 45
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 46
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 47
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 48
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 100 --seed 49
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 0
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 1
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 2
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 3
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 4
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 5
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 6
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 7
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 8
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 9
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 10
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 11
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 12
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 13
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 14
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 15
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 16
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 17
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 18
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 19
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 20
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 21
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 22
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 23
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 24
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 25
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 26
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 27
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 28
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 29
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 30
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 31
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 32
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 33
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 34
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 35
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 36
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 37
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 38
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 39
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 40
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 41
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 42
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 43
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 44
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 45
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 46
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 47
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 48
python main.py --rendermode none --colormap Set1 --logfile ./output-sanity/log.txt --dataset circle --criterion lrp --numsamples 200 --seed 49
